User implementation
Currus1/cuddly-sniffle-frontend pull request #7
Opened 2022-09-26 06:51 UTC by PijusZl

Padarytas user dizainas. Lentelė turėtų veikti ir paduoti įvestus duomenis į API, taip pat juos ir gauti.

2022-09-26 07:57 UTC, Tedas1 requested changes

2022-09-26 07:57 UTC, Tedas1 commented on src/UIcomponents/UserComponent.jsx
> +import { useEffect } from 'react'
Nepanaudotas importas

2022-09-26 07:57 UTC, Tedas1 commented on src/UIcomponents/UserComponent.jsx
> +            axios.post('http://localhost:5236/User/Adding/',{
Šiaip reiktų tik UserAPI palikt

2022-09-26 07:57 UTC, Tedas1 commented on src/UIcomponents/UserComponent.jsx
> +        axios.get('http://localhost:5236/User/Users')
Šiaip reiktų tik UserAPI palikt

2022-09-26 07:57 UTC, Tedas1 commented on package-lock.json
> +        "@emotion/react": "^11.10.4",
Ar visus šitus dependencies naudoji?

2022-09-26 07:57 UTC, Tedas1 commented on package-lock.json
> +        "@emotion/react": "^11.10.4",
tie mui, tanstack, emotion, moment, datepicker. Jeigu čia iš Klaido, tai geriau ištrinti

2022-09-26 07:57 UTC, Tedas1 commented on src/UIcomponents/UserComponent.jsx
> +import { TableRow } from '@mui/material'
Naudoji ? {TableRow}

2022-09-26 07:59 UTC, Tedas1 commented on src/UIcomponents/UserComponent.jsx
> +import { useEffect } from 'react'
{useEffect}

2022-09-26 07:59 UTC, Tedas1 commented on src/UIcomponents/UserComponent.jsx
> +import { useEffect } from 'react'
Jei naudosi vėliau, kabink prieš viršaus, kur useState

2022-09-26 08:04 UTC, Tedas1 commented
Reikia pamatyt vaizdą, fotkę įkelk

2022-09-26 19:35 UTC, Tedas1 requested changes

2022-09-26 19:35 UTC, Tedas1 commented on src/UserServices/UserAPI.js
> +        axios.post('http://localhost:5236/User/Adding/',{
Tikrinai ar veikia?

2022-09-27 11:22 UTC, Tedas1 approved these changes

2022-09-27 13:36 UTC, ClydeeS approved these changes
liuks

2022-09-27 20:21 UTC, merged